-- DCD 1.0 - Esquema inicial Supabase / PostgreSQL
-- Ejecutar en Supabase > SQL Editor > New query.

create table if not exists public.dcd_borradores (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    codigo_borrador text unique not null,
    app_version text not null default 'DCD 1.0',
    estado text not null default 'borrador',
    area text not null,
    unidad_docente text not null,
    codigo_unidad text,
    observaciones text
);

create table if not exists public.dcd_registros (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    codigo_borrador text not null references public.dcd_borradores(codigo_borrador) on delete cascade,
    estado text not null default 'borrador',
    area text not null,
    unidad_docente text not null,
    codigo_unidad text,
    columna_excel text,
    nivel_i text not null,
    nivel_ii text not null,
    rama text not null,
    titulacion text not null,
    numero_alumnos integer not null default 0,
    constraint dcd_registros_unicos unique (codigo_borrador, nivel_i, nivel_ii, rama, titulacion)
);

create index if not exists idx_dcd_registros_codigo_borrador
on public.dcd_registros(codigo_borrador);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_dcd_borradores_updated_at on public.dcd_borradores;
create trigger trg_dcd_borradores_updated_at
before update on public.dcd_borradores
for each row execute function public.set_updated_at();

drop trigger if exists trg_dcd_registros_updated_at on public.dcd_registros;
create trigger trg_dcd_registros_updated_at
before update on public.dcd_registros
for each row execute function public.set_updated_at();

-- Para una primera versión simple usando una clave de servicio desde Streamlit,
-- no hace falta activar Row Level Security.
-- Cuando el aplicativo pase a producción real, convendrá revisar seguridad/RLS.
