-- DCD 1.0 / 1.0.5 - Esquema Supabase / PostgreSQL
-- Ejecutar en Supabase > SQL Editor > New query.
-- Este SQL sirve tanto para proyecto nuevo como para actualizar la versión 1.0.

create table if not exists public.dcd_borradores (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    codigo_borrador text unique not null,
    app_version text not null default 'DCD 1.0',
    estado text not null default 'borrador',
    area text not null,
    unidad_docente text not null,
    codigo_unidad text,
    observaciones text,
    usuario_propietario text,
    usuario_ultima_edicion text
);

alter table public.dcd_borradores
add column if not exists usuario_propietario text;

alter table public.dcd_borradores
add column if not exists usuario_ultima_edicion text;

create table if not exists public.dcd_registros (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    codigo_borrador text not null references public.dcd_borradores(codigo_borrador) on delete cascade,
    estado text not null default 'borrador',
    area text not null,
    unidad_docente text not null,
    codigo_unidad text,
    columna_excel text,
    usuario_propietario text,
    nivel_i text not null,
    nivel_ii text not null,
    rama text not null,
    titulacion text not null,
    numero_alumnos integer not null default 0,
    constraint dcd_registros_unicos unique (codigo_borrador, nivel_i, nivel_ii, rama, titulacion)
);

alter table public.dcd_registros
add column if not exists usuario_propietario text;

create table if not exists public.dcd_auditoria (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    usuario text,
    rol text,
    accion text not null,
    detalle text,
    codigo_borrador text,
    area text,
    unidad_docente text
);

create table if not exists public.dcd_usuarios (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    username text unique not null,
    display_name text not null,
    role text not null default 'usuario',
    area text,
    unidad_docente text,
    codigo_unidad text,
    password_hash text not null,
    activo boolean not null default true,
    must_change_password boolean not null default true,
    constraint dcd_usuarios_role_check check (role in ('admin', 'usuario'))
);

create index if not exists idx_dcd_registros_codigo_borrador
on public.dcd_registros(codigo_borrador);

create index if not exists idx_dcd_auditoria_codigo_borrador
on public.dcd_auditoria(codigo_borrador);

create index if not exists idx_dcd_auditoria_created_at
on public.dcd_auditoria(created_at);

create index if not exists idx_dcd_usuarios_username
on public.dcd_usuarios(username);

create index if not exists idx_dcd_borradores_unidad_docente
on public.dcd_borradores(unidad_docente);

create index if not exists idx_dcd_borradores_usuario_propietario
on public.dcd_borradores(usuario_propietario);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_dcd_borradores_updated_at on public.dcd_borradores;
create trigger trg_dcd_borradores_updated_at
before update on public.dcd_borradores
for each row execute function public.set_updated_at();

drop trigger if exists trg_dcd_registros_updated_at on public.dcd_registros;
create trigger trg_dcd_registros_updated_at
before update on public.dcd_registros
for each row execute function public.set_updated_at();

drop trigger if exists trg_dcd_usuarios_updated_at on public.dcd_usuarios;
create trigger trg_dcd_usuarios_updated_at
before update on public.dcd_usuarios
for each row execute function public.set_updated_at();

-- Seguridad/RLS:
-- Para esta versión Streamlit usa clave de servidor guardada en Secrets.
-- No actives ni expongas claves en GitHub.
-- Cuando se cree un control real de usuarios por unidad docente, revisaremos RLS/policies.
